import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils"
import HomeNavbar from "./ui/HomeNavbar";
import { auth } from "@/auth";
// import AdminNavbar from "./ui/AdminNavbar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ss = await auth();
  // const checkAdmin = !!ss?.user;
  // console.log("Check if it's admin = ", checkAdmin);
  
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased light",
          fontSans.variable
        )}>
          {/* { !checkAdmin && <HomeNavbar /> } */}
          {children}
        </body>
    </html>
  );
}
