import type { Metadata } from "next";

import { cn } from "@/lib/utils"
import AdminLayoutResizable from "@/app/ui/AdminLayoutResizable";
import { auth } from "@/auth";
import Providers from "./providers";
import { getAllMenusData } from "@/app/lib/strapi";

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by me",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const sessionData = await auth();
  const token: any = sessionData?.user?.token;
  const data: any = await getAllMenusData(token);
  
  return (
      <div className={cn(
          "min-h-screen font-sans antialiased bg-background dark text-primary",
        )}>
          <Providers>
          <AdminLayoutResizable childrenx={children} data={data} />
          </Providers>
        </div>
  );
}
